// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Renamer.Data.Entities;

namespace Renamer.Data.Migrations
{
    [DbContext(typeof(EpisodeContext))]
    [Migration("20190427123946_AddIsActive")]
    partial class AddIsActive
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Renamer.Data.Entities.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AbsoluteNumber");

                    b.Property<int?>("AiredEpisodeNumber");

                    b.Property<int?>("AiredSeasonId");

                    b.Property<string>("EpisodeName")
                        .IsRequired();

                    b.Property<DateTime>("LastUpdated");

                    b.Property<int?>("Season");

                    b.Property<int>("SeriesId");

                    b.Property<int>("TVDBEpisodeId");

                    b.HasKey("Id");

                    b.HasAlternateKey("TVDBEpisodeId");

                    b.HasIndex("SeriesId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Renamer.Data.Entities.TVShow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsActive");

                    b.Property<int>("SeriesId");

                    b.Property<string>("SeriesName");

                    b.Property<string>("SeriesNamePreferred");

                    b.HasKey("Id");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("Renamer.Data.Entities.UserFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("SeriesId");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("Renamer.Data.Entities.Episode", b =>
                {
                    b.HasOne("Renamer.Data.Entities.TVShow")
                        .WithMany("Episodes")
                        .HasForeignKey("SeriesId")
                        .HasPrincipalKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
