// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Renamer.Data.Entities;

namespace Renamer.Data.Migrations
{
    [DbContext(typeof(EpisodeContext))]
    partial class EpisodeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("Renamer.Data.Entities.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AiredSeasonId");

                    b.Property<string>("EpisodeName");

                    b.Property<DateTime>("FirstAired");

                    b.Property<int>("Season");

                    b.Property<int>("SeriesId");

                    b.Property<int>("TVDBEpisodeId");

                    b.Property<int?>("TVSeriesId");

                    b.HasKey("Id");

                    b.HasIndex("TVSeriesId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Renamer.Data.Entities.TVSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("SeriesId");

                    b.Property<string>("SeriesName");

                    b.Property<string>("SeriesNamePreferred");

                    b.Property<int?>("UserFavoritesId");

                    b.HasKey("Id");

                    b.HasIndex("UserFavoritesId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("Renamer.Data.Entities.UserFavorites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("SeriesId");

                    b.HasKey("Id");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("Renamer.Data.Entities.Episode", b =>
                {
                    b.HasOne("Renamer.Data.Entities.TVSeries")
                        .WithMany("Episodes")
                        .HasForeignKey("TVSeriesId");
                });

            modelBuilder.Entity("Renamer.Data.Entities.TVSeries", b =>
                {
                    b.HasOne("Renamer.Data.Entities.UserFavorites")
                        .WithMany("Series")
                        .HasForeignKey("UserFavoritesId");
                });
#pragma warning restore 612, 618
        }
    }
}
